spring.application.name=tmill-bot
bot.token=${TELEGRAM_BOT_TOKEN}
# Mapeando o token do TMDB para o Spring
tmdb.token=${TMDB_READ_TOKEN}
tmdb.api.url=https://api.themoviedb.org/3
server.port=8082
# Em vez de api.openai.com, use o seu IP local ou localhost
openai.api.url=http://localhost:10300/v1/audio/transcriptions
openai.api.key=sk-local-no-key-needed
groq.api.key=${GROQ_API_KEY}
t1000.features.transcription-enabled=${TRANSCRIPTION_ENABLED:false}
logging.level.net.ddns.adambravo79.tmill=DEBUG
spring.threads.virtual.enabled=true